CREATE SCHEMA IF NOT EXISTS schema;

DROP TABLE IF EXISTS person, company, location, goods;

CREATE TABLE IF NOT EXISTS person
(
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(30) not null,
    sur_name   varchar(30) not null,
    balance    integer,
    address    varchar(255),
    phone      varchar(30)
);

CREATE TABLE IF NOT EXISTS company
(
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(30) not null,
    balance integer,
    address varchar(255),
    phone   varchar(30)
);

CREATE TABLE IF NOT EXISTS location
(
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_name varchar(30),
    shelf_number   int
);

CREATE TABLE IF NOT EXISTS goods
(
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(255),
    quantity int,
    price    int
);