CREATE SCHEMA IF NOT EXISTS schema;

DROP TABLE IF EXISTS schema.person;
DROP TABLE IF EXISTS schema.company;
DROP TABLE IF EXISTS schema.location;
DROP TABLE IF EXISTS schema.goods;

CREATE TABLE IF NOT EXISTS schema.person
(
    id         bigserial GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(30) not null,
    sur_name   varchar(30) not null,
    balance    integer,
    address    varchar(255),
    phone      varchar(30),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS schema.company
(
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(30) not null,
    balance integer,
    address varchar(255),
    phone   varchar(30)
);

CREATE TABLE IF NOT EXISTS schema.location
(
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_name varchar(30),
    shelf_number   int
);

CREATE TABLE IF NOT EXISTS schema.goods
(
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(255),
    quantity int,
    price    int
);